name: webhook_env
channels:
  - defaults
dependencies:
  - python=3.13.7
  - numpy=2.3.3
  - pandas=2.3.2
  - sqlite=3.50.2
  - requests=2.32.5
  - pytz=2025.2
  - python-dotenv=1.1.0
  - matplotlib=3.10.6
  - seaborn=0.13.2
