version: '3.9'

services:
  bikelogger:
    build: .
    image: flatiron_flows:latest
    container_name: flatiron_flows
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped