FROM continuumio/miniconda3

COPY ./python/bike_logs.py /app/bike_logs.py
WORKDIR /app
ADD environment.yml /tmp/environment.yml
RUN conda env create -f /tmp/environment.yml && \
    echo "source activate $(head -1 /tmp/environment.yml | cut -d' ' -f2)" > ~/.bashrc

RUN apt update && \
    apt install -y cron

RUN chmod 0644 /my-crontab

RUN crontab /my-crontab

RUN chmod +x /bike_logs.py

ENTRYPOINT ["/entrypoint.sh"]