name: bikeLog_env
channels:
  - defaults
dependencies:
  - python=3.13.5
  - numpy=2.3.1
  - pandas=2.3.1
  - sqlite=3.50.2
  - requests=2.32.4
  - lxml=5.3.0
  - pathlib=1.0.1
  - python-dotenv=1.1.0
